n=fscanf(fp2,"%d",&n);
for(i=1;i<=n;i++)
  fscanf(fp2,"%c",&f[i]);
for(i=1;i<=n;i++)
	fscanf(fp2,"%d",&w[i]);
HuffmanCoding(&HT,&HC,w,n);
q=&HT[2*n-1];
while(1)
	{
		ch=fgetc(fp2);
		if(feof(fp2)) break;
		i=7;
		while(ch!=0)
		{
			ch=ch/2;
			c=ch%2;
			d[i]=c;
			i--;
		}
		for(i=0;i<8;i++)
			{
				if(q->lchild==0&&q->rchild==0)
					for(j=1;j<=n;j++)
						if(q==HT+j)
							{
								fprintf(fp3,"%c",f[j]);
								q=&HT[2*n-1];break;
						    }//if
				if(d[i]==0)
				  q=q->lchild;
				else
					q=q->rchild;
		   }//for
	}